version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "4444:8080"
    volumes:
      - ./api.json:/foo/api.json
    environment:
      - SWAGGER_JSON=/foo/api.json
