include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
analyzer:
  errors:
    # allow for asset_does_not_exist
    unrecognized_error_code: ignore
    # ignore this in pubspec.yaml
    asset_does_not_exist: ignore