import type { Metadata } from 'next';
import 'styles/global.css';
import React from 'react';
import TanstackProvider from '@/providers/TanstackProvider';
import StyledComponentsRegistry from '@/lib/registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </TanstackProvider>
      </body>
    </html>
  );
}
