import type { Metadata } from 'next';
import 'styles/global.css';
import React from 'react';
import TanstackProvider from '@/providers/TanstackProvider';
import StyledComponentsRegistry from '@/lib/registry';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <StyledComponentsRegistry>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </StyledComponentsRegistry>
        </TanstackProvider>
      </body>
    </html>
  );
}
