name: Backend CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Choose the Node.js version you are using

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build project
        run: |
          cd backend
          npm run build

      - name: Install production dependencies
        run: |
          cd backend/build
          npm install --only=production

      - name: Start the application
        run: |
          cd backend/build
          npm start
