
name: Mobile App

on:
    push:
      branches:
        - 'main'
      paths:
        - 'mobile/**'
    pull_request:
      branches-ignore:
        - 'main'
      paths:
        - 'mobile/**'
jobs:
  mobile-app-format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Change directory to mobile
        run: cd mobile
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format .
      - name: Commit and push changes
        run: git diff --exit-code || { git config user.name "GitHub Actions"; git config user.email "actions@github.com"; git add .; git commit -m "Apply dart formatting"; git push origin $GITHUB_REF; }
      - name: Run analyze
        run: flutter analyze
      - name: Build mobile app
        run: flutter build apk --release