
name: Web App

on:
  push:
    branches:
      - '**'
    paths:
      - 'web-app/**'

jobs:
  web-app-lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./web-app
        run: yarn install

      - name: Run Prettier
        working-directory: ./web-app
        run: |
          npx prettier --write .
          echo "Prettier formatting done."

      - name: Commit and push changes
        run: git diff --exit-code || { git config user.name "GitHub Actions"; git config user.email "actions@github.com"; git add .; git commit -m "Apply Prettier formatting"; git push origin $GITHUB_REF; }

      - name: Run lint
        working-directory: ./web-app
        run: yarn lint

      - name: Build project
        working-directory: ./web-app
        run: yarn build