
name: Wep App

on:
  push:
    branches:
      - '*'

jobs:
  wep-app-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Run Prettier
        working-directory: ./web-app
        run: |
          npx prettier --write .
          echo "Prettier formatting done."

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'contact@latableronde.org'
          git add -A
          git commit -m "Apply Prettier formatting" || echo "No changes to commit"
          git push
  wep-app-lint:
    runs-on: ubuntu-latest
    needs: wep-app-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 'lts/*'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./web-app
        run: yarn install

      - name: Run lint
        working-directory: ./web-app
        run: yarn lint
  wep-app-build:
    runs-on: ubuntu-latest
    needs: wep-app-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./web-app
        run: yarn install

      - name: Build project
        working-directory: ./web-app
        run: yarn build