
name: Wep App Lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 'lts/*'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./web-app
        run: yarn install

      - name: Run lint
        working-directory: ./web-app
        run: yarn lint